name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build
    - name: run
      run: ./Release/WhatToDoNow
      
  clang-tidy:
      name: clang-tidy
      runs-on: ubuntu-latest
      steps:
        - name: clang-tidy check
          uses: smay1613/clang-tidy-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
