name: C/C++ CI

on: [push]

jobs:
  CppCkeck:
      name: CppCkeck
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: CppCheck
          uses: pouralijan/CppCheck@master
      env:
          DIRS: src
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build
    - name: run
      run: ./Release/WhatToDoNow
